name: Build Android Dev
on: [push]

jobs:
  install-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: tamacroft/pl-scf
          token: ${{ secrets.GH_TOKEN }}
      - name: Install npm dependencies and env
        run: |
          yarn install
        env:
          BASE_URL: ${{secrets.BASE_URL}}
          HOST: ${{ secrets.HOST }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          STORAGE_KEY: ${{ secrets.STORAGE_KEY }}
          DESIGN_WIDTH: ${{ secrets.DESIGN_WIDTH }}
      - name: Build APK
        run: |
          yarn build:apk
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/